import Link from 'next/link';
import {Header,Footer} from '../components';
import {getPublishedRedBooks} from '@/lib/publications';

export const dynamic = 'force-dynamic';

export default async function Red(){
  const books = await getPublishedRedBooks();
  return <><Header/><section className="pageHero"><div className="container"><div style={{fontSize:10,letterSpacing:'.11em',textTransform:'uppercase',fontWeight:800,color:'#b32328',marginBottom:4}}>Official Journal</div><h1>RED: The Research Journal e-Journal</h1><p style={{fontSize:12.5,color:'#607080',margin:'7px 0 0'}}>Electronic · Scholarly · Multidisciplinary Research Publication</p></div></section><main className="container" style={{padding:'22px 0 34px'}}>
    <section className="contentCard" style={{borderTop:'4px solid #cb2528'}}><div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(220px,320px)',gap:20,alignItems:'start'}}><div><h2 style={{marginTop:0}}>Journal Information</h2><p>RED: The Research Journal e-Journal is an electronic research journal published by the Institute of Research Education and Development (IRED) with the objective of promoting online dissemination of scholarly and research-based knowledge.</p><p>The journal welcomes multidisciplinary academic contributions across Arts, Humanities, Sciences, Social Sciences, Commerce, Education, Management, Law and other related disciplines.</p><div style={{fontSize:11.5,lineHeight:1.7,color:'#526577'}}><strong>Publishing Body & Publisher:</strong> Institute of Research Education and Development (IRED)<br/><strong>Official Address:</strong> A-3, 3rd Floor, Gita Apartment, Nr. Hirabaug Crossing, Ambawadi, Ahmedabad-380015, Gujarat, India.<br/><strong>Email:</strong> ired.foundation@gmail.com</div><div style={{marginTop:14,display:'flex',gap:8,flexWrap:'wrap'}}><Link className="btn btnOutline compact" href="/journal-information">Full Journal Information</Link><Link className="btn btnOutline compact" href="/editorial-board">Editorial Board</Link></div></div><img className="redJournalLogo" src="/red-logo.svg?v=5" alt="RED: The Research Journal e-Journal" style={{width:'100%',maxHeight:120,objectFit:'contain'}}/></div></section>
    <div className="contentCard"><h2 style={{marginTop:0}}>Published RED e-Journal Publications</h2><p>Published RED research content and compiled scholarly editions are listed below.</p><div className="listPanel">{books.length ? books.map((b)=>{
    const dateLabel = [b.publication_month,b.publication_year].filter(Boolean).join(' ') || b.publication_label || '';
    return <div className="bookRow" key={b.id} style={{alignItems:'flex-start'}}>{b.cover_url ? <img src={b.cover_url} alt={`${b.title} cover`} style={{width:92,height:124,objectFit:'cover',border:'1px solid #e0e0e0',borderRadius:4,flex:'0 0 auto'}}/> : <div className="bookCover">RED<br/>Research<br/>Journal</div>}<div className="itemMain"><div className="itemTitle">{b.title}</div>{b.subtitle ? <div className="meta">{b.subtitle}</div> : null}<div className="meta">{b.editors ? `Edited by ${b.editors}` : 'IRED Research Publication'}</div><div className="meta">{dateLabel}{b.volume ? ` · Volume ${b.volume}` : ''}{b.issue ? ` · Issue ${b.issue}` : ''}</div>{b.issn ? <div className="meta">ISSN: {b.issn}</div> : null}{b.description ? <p style={{fontSize:12,lineHeight:1.55,margin:'7px 0 0',color:'#526577'}}>{b.description}</p> : null}</div><div className="actions"><a className="smallBtn" href={b.view_url}>View Publication</a></div></div>
  }) : <div style={{padding:'18px 0',color:'#687586'}}>No published RED e-Journal publications yet.</div>}</div></div></main><Footer/></>}
