'use client'

import { FormEvent, useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type Settings={
  institution_name:string;institution_short_name:string;motto:string;publisher_name:string;official_address:string;
  green_title:string;green_description:string;green_scope:string;green_editor_in_chief:string;
  red_title:string;red_description:string;red_scope:string;
  first_volume_year:number;article_id_prefix:string;doi_prefix:string;submission_status:string;
  homepage_kicker:string;homepage_title:string;homepage_highlight:string;homepage_description:string;homepage_notice:string;
  seo_title:string;seo_description:string;seo_keywords:string;
}

const defaults:Settings={
  institution_name:'Institute of Research Education and Development',institution_short_name:'IRED',motto:'Knowledge for a Better Tomorrow',publisher_name:'Institute of Research Education and Development (IRED)',official_address:'A-3, 3rd Floor, Gita Apartment, Nr. Hirabaug Crossing, Ambawadi, Ahmedabad-380015, Gujarat, India.',
  green_title:'GREEN: The Research Journal',green_description:'International, peer-reviewed, open-access multidisciplinary research journal for original research papers and scholarly articles.',green_scope:'Accounting, Archaeology, Biology, Business, Chemistry, Commerce, Economics, Education, Law, Linguistics, Management, Physics, Political Science, Social Work, Arts, Humanities, Sciences, Social Sciences and related academic disciplines.',green_editor_in_chief:'Dr. Bhavika Kadikar — Librarian and Assistant Professor, Surendranagar University, Wadhwan',
  red_title:'RED: The Research Journal e-Journal',red_description:'Electronic research journal for online dissemination of scholarly and research-based knowledge across multiple academic disciplines.',red_scope:'Multidisciplinary research across Arts, Humanities, Sciences, Social Sciences, Commerce, Education, Management, Law and other academic disciplines.',
  first_volume_year:2026,article_id_prefix:'GREEN',doi_prefix:'',submission_status:'Open for Submission',
  homepage_kicker:'Research · Education · Development',homepage_title:'Research Knowledge',homepage_highlight:'for a Better Tomorrow',homepage_description:'A platform for researchers, academicians, and students to share knowledge and create a positive impact.',homepage_notice:'',
  seo_title:'IRED | GREEN: The Research Journal & RED: The Research Journal e-Journal',seo_description:'Official publication website of the Institute of Research Education and Development (IRED), publisher of GREEN: The Research Journal and RED: The Research Journal e-Journal.',seo_keywords:'IRED, Institute of Research Education and Development, GREEN: The Research Journal, RED: The Research Journal e-Journal, peer-reviewed journal, open-access journal, research journal, academic publications'
}

const sectionStyle={border:'1px solid #d9e2e8',background:'#fff',padding:16} as const
const label={display:'block',fontSize:11,fontWeight:800,color:'#40566a'} as const
const field={display:'block',width:'100%',marginTop:5,padding:'10px 11px',border:'1px solid #cbd6de',background:'#fff',fontSize:12} as const
const area={...field,minHeight:86,resize:'vertical' as const}

export default function WebsiteSettingsManager(){
  const supabase=createClient();const [form,setForm]=useState<Settings>(defaults);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('')
  useEffect(()=>{void(async()=>{const {data,error}=await supabase.from('site_settings').select('*').eq('id',true).maybeSingle();if(error){setMessage(error.message);return}if(data)setForm({...defaults,...data})})()},[])
  function set<K extends keyof Settings>(key:K,value:Settings[K]){setForm(v=>({...v,[key]:value}))}
  async function save(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Admin session expired. Please sign in again.');const cleaned={...form,institution_name:form.institution_name.trim(),institution_short_name:form.institution_short_name.trim(),motto:form.motto.trim(),publisher_name:form.publisher_name.trim(),official_address:form.official_address.trim(),article_id_prefix:form.article_id_prefix.trim().toUpperCase(),doi_prefix:form.doi_prefix.trim(),seo_title:form.seo_title.trim(),seo_description:form.seo_description.trim(),updated_at:new Date().toISOString(),updated_by:user.id};if(!cleaned.institution_name||!cleaned.publisher_name||!cleaned.green_title||!cleaned.red_title)throw new Error('Institution, publisher and journal titles are required.');if(cleaned.first_volume_year<1900||cleaned.first_volume_year>2100)throw new Error('Enter a valid first volume year.');const {error}=await supabase.from('site_settings').upsert({id:true,...cleaned},{onConflict:'id'});if(error)throw error;setMessage('Website settings updated successfully.');}catch(error){setMessage(error instanceof Error?error.message:'Could not save website settings.')}finally{setBusy(false)}}
  async function restore(){if(!confirm('Restore default website settings?'))return;setBusy(true);setMessage('');try{const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('site_settings').upsert({id:true,...defaults,updated_at:new Date().toISOString(),updated_by:user?.id||null},{onConflict:'id'});if(error)throw error;setForm(defaults);setMessage('Default website settings restored.')}catch(error){setMessage(error instanceof Error?error.message:'Could not restore defaults.')}finally{setBusy(false)}}
  return <form onSubmit={save} style={{display:'grid',gap:14,marginTop:20}}>
    {message?<div style={{padding:'10px 12px',border:'1px solid #cbdde8',background:'#f3f8fb',fontSize:11.5}}>{message}</div>:null}
    <section style={sectionStyle}><h2 style={{margin:'0 0 12px'}}>Institution</h2><div style={{display:'grid',gridTemplateColumns:'1fr 180px',gap:12}}><label style={label}>Institution Name<input style={field} value={form.institution_name} onChange={e=>set('institution_name',e.target.value)}/></label><label style={label}>Short Name<input style={field} value={form.institution_short_name} onChange={e=>set('institution_short_name',e.target.value)}/></label></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12,marginTop:12}}><label style={label}>Motto<input style={field} value={form.motto} onChange={e=>set('motto',e.target.value)}/></label><label style={label}>Publisher Name<input style={field} value={form.publisher_name} onChange={e=>set('publisher_name',e.target.value)}/></label></div><label style={{...label,marginTop:12}}>Official Address<textarea style={area} value={form.official_address} onChange={e=>set('official_address',e.target.value)}/></label></section>
    <section style={sectionStyle}><h2 style={{margin:'0 0 12px'}}>Journals</h2><label style={label}>GREEN Official Title<input style={field} value={form.green_title} onChange={e=>set('green_title',e.target.value)}/></label><label style={{...label,marginTop:10}}>GREEN Description<textarea style={area} value={form.green_description} onChange={e=>set('green_description',e.target.value)}/></label><label style={{...label,marginTop:10}}>GREEN Scope<textarea style={area} value={form.green_scope} onChange={e=>set('green_scope',e.target.value)}/></label><label style={{...label,marginTop:10}}>GREEN Editor in Chief<input style={field} value={form.green_editor_in_chief} onChange={e=>set('green_editor_in_chief',e.target.value)}/></label><div style={{height:1,background:'#e1e7eb',margin:'16px 0'}}/><label style={label}>RED Official Title<input style={field} value={form.red_title} onChange={e=>set('red_title',e.target.value)}/></label><label style={{...label,marginTop:10}}>RED Description<textarea style={area} value={form.red_description} onChange={e=>set('red_description',e.target.value)}/></label><label style={{...label,marginTop:10}}>RED Scope<textarea style={area} value={form.red_scope} onChange={e=>set('red_scope',e.target.value)}/></label></section>
    <section style={sectionStyle}><h2 style={{margin:'0 0 12px'}}>Publication Settings</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12}}><label style={label}>First Volume Year<input type="number" style={field} value={form.first_volume_year} onChange={e=>set('first_volume_year',Number(e.target.value))}/></label><label style={label}>Article ID Prefix<input style={field} value={form.article_id_prefix} onChange={e=>set('article_id_prefix',e.target.value)}/></label><label style={label}>DOI Prefix<input style={field} placeholder="Optional" value={form.doi_prefix} onChange={e=>set('doi_prefix',e.target.value)}/></label><label style={label}>Submission Status<input style={field} value={form.submission_status} onChange={e=>set('submission_status',e.target.value)}/></label></div></section>
    <section style={sectionStyle}><h2 style={{margin:'0 0 12px'}}>Homepage</h2><label style={label}>Kicker<input style={field} value={form.homepage_kicker} onChange={e=>set('homepage_kicker',e.target.value)}/></label><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12,marginTop:10}}><label style={label}>Main Title<input style={field} value={form.homepage_title} onChange={e=>set('homepage_title',e.target.value)}/></label><label style={label}>Highlighted Line<input style={field} value={form.homepage_highlight} onChange={e=>set('homepage_highlight',e.target.value)}/></label></div><label style={{...label,marginTop:10}}>Homepage Description<textarea style={area} value={form.homepage_description} onChange={e=>set('homepage_description',e.target.value)}/></label><label style={{...label,marginTop:10}}>Announcement / Notice<textarea style={area} placeholder="Leave blank to hide notice" value={form.homepage_notice} onChange={e=>set('homepage_notice',e.target.value)}/></label></section>
    <section style={sectionStyle}><h2 style={{margin:'0 0 12px'}}>SEO & Search Metadata</h2><label style={label}>Website SEO Title<input style={field} value={form.seo_title} onChange={e=>set('seo_title',e.target.value)}/></label><label style={{...label,marginTop:10}}>SEO Description<textarea style={area} value={form.seo_description} onChange={e=>set('seo_description',e.target.value)}/></label><label style={{...label,marginTop:10}}>SEO Keywords<textarea style={area} value={form.seo_keywords} onChange={e=>set('seo_keywords',e.target.value)}/></label></section>
    <div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="btn btnNavy" disabled={busy} type="submit">{busy?'Saving…':'Save Website Settings'}</button><button className="btn btnOutline" disabled={busy} type="button" onClick={restore}>Restore Defaults</button></div>
  </form>
}
