import type { Metadata } from 'next'
import { Header,Footer } from '../components'
import {getContactSettings} from '@/lib/contact-settings'
import {getSiteSettings} from '@/lib/site-settings'

export const metadata:Metadata={title:'Privacy Policy',description:'Privacy policy for the Institute of Research Education and Development publication website.'}

export default async function PrivacyPage(){
  const [contact,settings]=await Promise.all([getContactSettings(),getSiteSettings()])
  return <><Header/><section className="pageHero"><div className="container"><h1>Privacy Policy</h1><p>IRED research publication website privacy information.</p></div></section><main className="container" style={{padding:'22px 0 34px'}}><article className="contentCard" style={{maxWidth:920,marginLeft:'auto',marginRight:'auto'}}><h2>Information We Receive</h2><p>IRED may receive contact details and scholarly publication information when authors, researchers, reviewers or other users contact the institute or submit material through the stated submission process. The public website does not require authors to upload manuscripts directly.</p><h2>How Information Is Used</h2><p>Information is used for academic communication, editorial administration, publication processing, record management and operation of the IRED research publication platform. Publication metadata intended for scholarly dissemination may appear publicly after editorial approval.</p><h2>Administrative Access</h2><p>Protected administrative areas require authenticated staff access. Administrative permissions are role-based and are intended only for authorized IRED personnel.</p><h2>External Services</h2><p>The website uses hosting, database and storage services necessary to operate the publication platform. Users should avoid sending passwords or other unnecessary sensitive information by email.</p><h2>Contact</h2><p>Questions about privacy can be sent to <strong>{contact.email}</strong> or <strong>{contact.secondary_email}</strong>.</p><p><strong>Institute Address:</strong> {settings.official_address}<br/><strong>Journal / Editorial Office:</strong> {settings.journal_office_address}</p></article></main><Footer/></>}
