import Link from 'next/link';
import {Header,Footer} from '../components';
import {getPublishedGreenPapers} from '@/lib/publications';

export const dynamic = 'force-dynamic';

export default async function Green(){
  const papers = await getPublishedGreenPapers();
  return <><Header/><section className="pageHero"><div className="container"><div style={{fontSize:10,letterSpacing:'.11em',textTransform:'uppercase',fontWeight:800,color:'#14733d',marginBottom:4}}>Official Journal</div><h1>GREEN: The Research Journal</h1><p style={{fontSize:12.5,color:'#607080',margin:'7px 0 0'}}>International · Peer-reviewed · Open-access · Multidisciplinary</p></div></section><main className="container" style={{padding:'22px 0 34px'}}>
    <section className="contentCard" style={{borderTop:'4px solid #148444'}}><div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(220px,320px)',gap:20,alignItems:'start'}}><div><h2 style={{marginTop:0}}>Journal Information</h2><p>GREEN: The Research Journal is an international, peer-reviewed, open-access research journal published by the Institute of Research Education and Development (IRED).</p><p>The journal publishes original and unpublished research papers and scholarly articles across Arts, Humanities, Sciences, Social Sciences, Commerce, Management and related disciplines.</p><div style={{fontSize:11.5,lineHeight:1.7,color:'#526577'}}><strong>Publishing Body & Publisher:</strong> Institute of Research Education and Development (IRED)<br/><strong>Editor in Chief:</strong> Dr. Bhavika Kadikar, Librarian and Assistant Professor, Surendranagar University, Wadhwan<br/><strong>Official Address:</strong> A-3, 3rd Floor, Gita Apartment, Nr. Hirabaug Crossing, Ambawadi, Ahmedabad-380015, Gujarat, India.<br/><strong>Email:</strong> ired.foundation@gmail.com</div><div style={{marginTop:14,display:'flex',gap:8,flexWrap:'wrap'}}><Link className="btn btnOutline compact" href="/journal-information">Full Journal Information</Link><Link className="btn btnOutline compact" href="/editorial-board">Editorial Board</Link></div></div><img src="/green-logo-family.svg?v=1" alt="GREEN: The Research Journal" style={{width:'100%',maxHeight:150,objectFit:'contain'}}/></div></section>
    <div className="contentCard"><h2 style={{marginTop:0}}>Published Research Papers</h2><p>Individual research papers and scholarly articles appear here after editorial approval and publication.</p><div className="listPanel">{papers.length ? papers.map((p)=><div className="paperRow" key={p.id}><div><div style={{fontSize:9.5,fontWeight:800,letterSpacing:'.07em',textTransform:'uppercase',color:'#14733d',marginBottom:3}}>{p.article_id||'GREEN Research Paper'}</div><div className="itemTitle">{p.title}</div><div className="meta">{p.authors}{p.publication_month ? ` · ${p.publication_month}` : ''}{p.publication_year ? ` ${p.publication_year}` : ''}{p.volume ? ` · Vol. ${p.volume}` : ''}{p.issue ? ` · Issue ${p.issue}` : ''}</div>{p.doi ? <div className="meta">DOI: {p.doi}</div> : null}</div><div className="actions"><Link className="smallBtn" href={`/green/view/${p.id}`}>View Details</Link>{p.download_url ? <a className="smallBtn filledGreen" href={p.download_url}>Download PDF</a> : null}</div></div>) : <div style={{padding:'18px 0',color:'#687586'}}>No published GREEN papers yet.</div>}</div></div></main><Footer/></>}
